baseUrl: 'http://$PRIMARY_SITE_URL/'
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Storybook Example'
primary: true
siteGroup: 04a80951-3484-4878-817a-b86a5714efdc # Storybook Example
sortOrder: 1
