dateModified: 1660515482
email:
  fromEmail: brian@brianhanson.net
  fromName: 'Storybook Example'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    04a80951-3484-4878-817a-b86a5714efdc: 'Storybook Example' # Storybook Example
    7cb5ad7e-d443-441b-a666-08963638ed06: Common # Common
    64c2f2ef-b9e7-44d0-b38c-15ab66bb4986: 'Storybook Example' # Storybook Example
plugins:
  storybook:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      storiesDirectory: '@root/stories'
system:
  edition: solo
  live: true
  name: 'Storybook Example'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
